### ISSUE TITLE
NOT working in androidx

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [rongi/klaster#6]
please add support for androidx

**Comment by rongi** [comment]
Have you seen this issue https://github.com/rongi/klaster/issues/4 ?

**Comment by NurseyitTursunkulov** [comment]
hello , I tryed it but it does not work

>

**Comment by rongi** [comment]
Thank you for the report. Have you tried all the stuff from that issue?

- delete build folders
- invalidate cache/restart in AS
- add android.enableJetifier=true and android.useAndroidX=true to gradle.properties
- upgrade Android Studio

If nothing of this helps, can you please provide me with a minimal project that reproduces this issue?

**Comment by rongi** [comment]
Closing this for now because not enough data to reproduce. Will reopen if more info is available.
